language: node_js
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: bfcC+WsJJir9gJjMXC+V1bB3wrdchYliYywwxmMDEEQmNbXyBXct7UUw2bINbf62pIA42HRyx5QnZNFO3A3dtHbfZZWNKGoUfwwkloXr39Fe3FCLB5um55M6BqbCh4mf4+aqqOO6qzHvc6FOiMQwBN6QRw77nAn5s/cDLdSBCDKbH6co5K/AZ6gYRpbozXLHhphhvxpEET+JaBZYLi8xwx59oDHfpHg9hmcTNSL0x4h5nyfo1UpQYD46X3EC8uW0Sab3Nk5rHqsiSi4yAWNdyrVozfxfJycixDTMG5sVqUc9a2qURAnMr+RjfasICIXSY0Im6UyCd5R4AW94XC2Ve/Ciug6qNo8P7EH/inkBzibi/JawwUb8so2NF6/+Jn9ggELqS/5IS27wP5IoirX5Z92cK+8KmhGPYhVXKv+zeqbv7khU+7SQclzEOMWSlsWGajdrMpe9sAmyBFFVwl+REZcBS+myB/yKflnVKqN14RgYwHuz05BsVnklAGkTLSc35Yp8cTlSTbPQtOl/oP2Cf20yiDEqkdVNE6tVudrDkTzt7OYYLdDT7aZ2tqpE7+47ZCI8SOoWeoqe0Zh+zpZjn+isnohTS6nvIx1ARtNo3NlAt7KKO/XQ1C6VwwcNX0rEPPvlIsuCZTj4NjgVeygneoXQ4CL2CYEqFCgynuEONGQ=
  file:
    - 'markdown-escapes.js'
    - 'markdown-escapes.min.js'
  on:
    tags: true
